version: '3.8'

services:
  web:
    build: .
    image: electro-app:latest
    restart: always
    volumes:
      # Mount the database directory to persist data
      - electro_db:/app/instance
      # Mount the uploads directory to persist images
      - electro_uploads:/app/static/uploads
    env_file:
      - .env

volumes:
  electro_db:
  electro_uploads:
